[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    z3t0/IRremote@^3.9.0
    adafruit/Adafruit_VL53L0X@^1.2.0
    arduino-libraries/LiquidCrystal@^1.0.7